### PR TITLE
Improving readme.md in 1.3.0

### LINKED ISSUE #35: Make readme.txt nicer and add more text about the features

### PR DESCRIPTION
**Pull request by carlosg-gh**
DO NOT MERGE YET!

It's not completed. Just leaving my progress here. I still have to fix the images and add more stuff.

Should fix #35 when finished.

### CODE REVIEW

**Comment by blackus3r** [comment]
Just a notice: this should also land in the readme.txt file :) Thanks, for the pull Request.

You can use the same images from wordpress. 

Here you find all images: https://plugins.svn.wordpress.org/post-worktime-logger/assets/

**Comment by blackus3r** [comment]
The readme.md is just for Github. The readme.txt is for wordpress, but at the moment, it's a bit empty on the page.

**Comment by carlosg-gh** [comment]
I've fixed the images. For some reason linking them directly from your link doesn't work, so I had to upload them to imgur. I'm not sure if you're okay with that, if you have any problem with it we could look for an alternative.

Also, may I ask what license are you using for this project? From the readme.txt I can't tell if you're using GPLv2 or GPLv3.

**Comment by blackus3r** [comment]
Thank you, 

I will have a look  later at it. (images) 

Could you please adjust the readme.txt file too? 

I see, I have a mismatch between the License tags. What do you think would be better? GPLv2 or v3?

**Comment by carlosg-gh** [comment]
Sure, I'll adjust the readme.txt, but I want to be fone with the readme.md first so I can make both of them similar. As I said, I still want to add a few things to the readme.md (like the license or a disclaimer).

About the license, honestly I don't have any idea. I'm really new to contributing, but I guess that GPLv3 would be better.

**Comment by blackus3r** [comment]
Okay, then we will take the GPLv3 licence. And we have to fix it in post-worktime-logger.php

**Comment by carlosg-gh** [comment]
Okay, everything should be done I believe. If you don't have any problem with the images being hosted in imgur, it should be ready to merge. Otherwise just tell me, we could do something like upload the screenshots to the repository and link them internally or something like that.

**Comment by blackus3r** [comment]
I have already thought about it several times,  and I think it is a good solution to host the images in the repository. 
So we have always the correct screenshots for the right version. 
You can download the assets folder and add it to your branch.

**Comment by carlosg-gh** [comment]
Done.

**Review by blackus3r — APPROVED** [review]
Nice work :) 
I will merge it later.

**Pull request merged**
