### PR TITLE
Add number of posts setting

### PR DESCRIPTION
**Pull request by selamanse**
Add a new section for statistics and a setting to control the number of
posts displayed on the top posts (worktime) chart

### CODE REVIEW

**Comment by selamanse** [comment]
addressing Issue #62

**Comment by blackus3r** [comment]
I thought to implememt this input on the statistic page. 
But I like this way more because the value is saved too. 
Nice work :+1:
I will merge this later.

**Comment by blackus3r** [comment]
Do you have a screenshot?

**Comment by selamanse** [comment]
I'll add a screenshot tomorrow :)

**Comment by selamanse** [comment]
numberofposts_setting

**Pull request merged**
