### PR TITLE
Fix #42

### LINKED ISSUE #42: Implement name constant
PWL_NAME = post-worktime-logger

### PR DESCRIPTION
**Pull request by mazzcris**
Should fix issue #42

### CODE REVIEW

**Comment by mazzcris** [comment]
Should fix issue #41

**Comment by blackus3r** [comment]
Nice work  👍

**Comment by blackus3r** [comment]
Did you tested that everything is still working?

**Comment by mazzcris** [comment]
I took a look around, my knowledge of the plugin is limited but everything seemed ok after the changes

**Comment by mazzcris** [comment]
I'll fix this as soon as i can

**Pull request merged**
