### PR TITLE
Add PHPCS, WPCS, and docs for how to use them

### LINKED ISSUE #38: Consider conforming to the WordPress Coding Standards
Since this is a WordPress plugin it might make sense to conform to the [WPCS](https://codex.wordpress.org/WordPress_Coding_Standards).

You can add PHPCS and PHPCBF integration so you can run reports to see what lines aren't matching the standard, and PHPCBF will automatically fix some of the issues found (the ones that can be fixed).

### PR DESCRIPTION
**Pull request by zachwills**
Resolves #38

### CODE REVIEW

**Comment by blackus3r** [comment]
Can you explain it to me. Which integration is needed for pull request checks?

**Comment by zachwills** [comment]
What do you mean? Are you asking how you can setup the 3rd party PR reviewer to check for WPCS?

**Comment by blackus3r** [comment]
Yes.

**Comment by zachwills** [comment]
Looks like you might not be able to specify a custom PHPCS ruleset: https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns

**Comment by blackus3r** [comment]
Okay, I will have a look later. 
Thanks for your work.

**Pull request merged**
