### PR TITLE
Add PayPal link at readme.md

### PR DESCRIPTION
**Pull request by za**
https://github.com/blackus3r/post-worktime-logger/issues/50

### CODE REVIEW

**Comment by blackus3r** [comment]
Please also add to readme.txt
Donate link: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=28WZAXQDXYZ5A

**Comment by blackus3r** [comment]
I have changed the base branch to swimlane/1.4.0

**Comment by za** [comment]
I've added the PayPal hyperlink at `readme.md`.

**Comment by blackus3r** [comment]
thanks, please also add it to readme.txt

**Comment by za** [comment]
@blackus3r I've added donation section at `readme.txt`

**Comment by blackus3r** [comment]
I added the donation link in the header. 

Thanks for all :-)

**Pull request merged**
