### PR TITLE
Move reset button to fix #43

### LINKED ISSUE #43: Move the reset button to a better position

### PR DESCRIPTION
**Pull request by mazzcris**
This should fix #43

### CODE REVIEW

**Comment by blackus3r** [comment]
Thanks, do you have a screenshot ?

**Comment by mazzcris** [comment]
button screenshot

**Comment by blackus3r** [comment]
Oh sorry, we have missunderstood us. 
I meant the other reset button. You will find it in the settings page. 
Please revert the changes for this button, because it is at a perfect position.

**Comment by mazzcris** [comment]
Ok no problem :) I will take a look to this as soon as I can

**Comment by mazzcris** [comment]
@blackus3r Something like this? (added a confirm popup, as the button could be clicked accidentally)
reset button

**Comment by blackus3r** [comment]
Nice, this is a good feature.. 

By the way, I have to merge your pull request in the right order. We have now conflicts...

**Comment by mazzcris** [comment]
I can fix my branch later in the evening

**Comment by blackus3r** [comment]
okay. 

it seems, that you have not checked out new after finishing the text domains. But no problem.

**Comment by mazzcris** [comment]
@blackus3r I'm sorry, should be ok now

**Comment by blackus3r** [comment]
I have to merge this https://github.com/blackus3r/post-worktime-logger/pull/44 first. But there are conflicts in the settings.php file. 

If everything is resolved, I can merge both pull requests.

**Comment by blackus3r** [comment]
@mazzcris Now we have here conflicts. Maybe the other pull requests has conflicts too.

**Comment by blackus3r** [comment]
@mazzcris can you please resolve the conflicts

**Comment by blackus3r** [comment]
Fixed conflicts: https://github.com/blackus3r/post-worktime-logger/pull/74

**Pull request closed without merging**
